version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 20
    commands:
      - echo "Ensuring no Terraform is present..."
      - rm -f /usr/local/bin/terraform || true
      - rm -f /bin/terraform || true
      - rm -rf ~/.terraform || true
      - pip install awscli
      - echo "Installing Terraform..."
      - curl -Lo /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.3.0/terraform_1.3.0_linux_amd64.zip
      - unzip -o /tmp/terraform.zip -d /usr/local/bin/
      - chmod +x /usr/local/bin/terraform
      - export PATH=$PATH:/usr/local/bin 
      - echo "Installing pnpm..."
      - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
      - cd frontend
      - npm install -g pnpm
      - pnpm install
      - cd ..
  pre_build:
    commands:
      - echo "Setting up environment..."
      - export AWS_REGION=eu-central-1
      - cd backend/terraform-aws-ec2
      - chmod +x deploy.sh
      - cd ../..
  build:
    commands:
      - echo "Building frontend..."
      - cd frontend
      - pnpm build
      - cd ../backend/terraform-aws-ec2
      - ./deploy.sh
  post_build:
    commands:
      - echo "Deployment completed successfully."

  artifacts:
    files:
      - '**/*'
