version: '3.8'

services:
  web:
    build:
      context: ./backend  # Zeigt auf den 'backend'-Ordner
    volumes:
      - ./backend:/app
      - ./backend/static:/app/static  # Statische Dateien
    expose:
      - "8000"
    env_file:
      - .env
    command: ["./wait-for-it.sh", "db:5432", "--", "gunicorn", "--bind", "0.0.0.0:8000", "orgagps.wsgi:application"]
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend  # Next.js-Frontend im 'frontend'-Ordner
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://nginx/api  # API-Aufruf über Nginx weiterleiten
    depends_on:
      - web

  db:
    image: postgres:13  # Verwende eine stabile Version von Postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/static:/app/static  # Statische Dateien für Nginx
    depends_on:
      - web
      - frontend

volumes:
  postgres_data:
