services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate && 
              gunicorn --workers 3 --bind 0.0.0.0:8000 orgagps.wsgi:application"
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
    ports:
      - "8000:8000"
    networks:
      - app-network
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/usr/src/app/staticfiles
    depends_on:
      - web
    networks:
      - app-network

  services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dcifp24!
      POSTGRES_DB: orgagps_database
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  static_volume:
  postgres-data:


networks:
  app-network:
    name: app-network
    driver: bridge
